name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, synchronize]

jobs:
  update-staging:
    name: 🌱 Merge to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'On Staging')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: 🖇️ Merge current branch into staging
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'staging'
          github_token: ${{ github.token }}

  update-development:
    name: 🛠 Merge to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'On Staging') || contains(github.event.pull_request.labels.*.name, 'On Development')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: 🖇️ Merge current branch into development
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'development'
          github_token: ${{ github.token }}
