name: Update development
on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled, synchronize]

jobs:
  update-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'On Development')
    steps:
      - uses: actions/checkout@v3
      - name: 🖇️ Merge current branch into development
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'development'
          github_token: ${{ github.token }}
